<html>
<head>
    <title>${project} Application</title>
</head>
<body>
<h1 class="title">Welcome to <code>${project}</code>, an
    application generated by the <a
            href="http://docs.pylonsproject.org/projects/pyramid/current/"
            >pyramid</a> web application framework.</h1>
<table>
    % for team in teams:
    <tr><td>${team.name}</td><td>${team.id}</td></tr>
    % endfor
</table>
</body>
</html>