"""empty message

Revision ID: 5eae5c591d4
Revises: 260ed01cee8d
Create Date: 2012-08-04 11:39:35.960493

"""

# revision identifiers, used by Alembic.
revision = '5eae5c591d4'
down_revision = '260ed01cee8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smsdelivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to', sa.String(), nullable=True),
    sa.Column('network_code', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('msisdn', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('err_code', sa.String(), nullable=True),
    sa.Column('scts', sa.String(), nullable=True),
    sa.Column('message_timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smsmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_name', sa.String(), nullable=True),
    sa.Column('to', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('num_message_parts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smsmessagepart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('sms_message_id', sa.Integer(), nullable=True),
    sa.Column('to', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('remaining_balance', sa.Integer(), nullable=True),
    sa.Column('message_price', sa.Integer(), nullable=True),
    sa.Column('error_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sms_message_id'], ['smsmessage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'slotuser', sa.Column('notify_sms_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'slotuser', 'notify_sms_id')
    op.drop_table('smsmessagepart')
    op.drop_table('smsmessage')
    op.drop_table('smsdelivery')
    ### end Alembic commands ###
